### ISSUE TITLE
Status and comparisons

### ISSUE THREAD

**Issue by mredaelli** [tek/amino#1]
I'm transitioning from Scala to Python for work, and I'm looking around for libraries to make the transition smoother.
I'm mostly relying on [this](https://github.com/sfermigier/awesome-functional-python#libraries) as a list of possible libraries, and while for, let say, "function magic" there seem to be good options, it would seem that for the "monad magic" the competitors are much less numerous.

fn.py and PyMonad haven't been updated in years, OSlash characterizes itself as a learning exercise, and then there's amino - which to me, without having tried any of them but just looking at docs, seems to be the best - but has an order of magnitude less stars than OSlash.

I was wondering if you could share your thoughts on the differences between amino and other similar libraries (those I listed, and others in case I missed some).
Also, in the README you mention performance penalties, but don't go into specifics of what parts of the library are more susceptible to those, and roughly how much penalty we are talking about. Could you elaborate on that?

Thanks!

**Comment by tek** [comment]
First of all, I have been moving most of my stuff to Haskell lately, so there's not been much activity here either. Especially the lack of HKTs in mypy has been a strong motivator to put in the work and rewrite several projects.
Nevertheless, I would still be open to investing a small proportion of my time if it made sense.

As far as I have observed, most libraries focus on syntactic magic and function composition, e.g. Hask implemented an elaborate dialect with Hindley-Milner to give you a sort of Haskell experience.
While I initially put some effort into lambda syntax with `_` and `__`, I abandoned that feature some time ago for several shortcomings like the mentioned runtime overhead, impossibilty to have it typechecked and just not wanting to invest weeks into making it sound and robust.
Towards to end, I tried to keep to standard python syntax constructs whenever possible, especially to be able to use mypy (for example, generating different `StateT` variants instead of using a parameterized class).

My focus was mainly on monadic generators, which I considered to be a very well working and indispensible feature, the scala-like typeclass system, mainly for the formal aspect of organizing functionality, and to provide a nontrivial standard library of fundamental concepts like Maybe, IO (or generally suspending algebras) and State that closesly resembles cats.

On a language level, there's also the `Dat` and `ADT` classes that allow, respectively, for generic data type programming and quite efficient (O(1) after having generated a global function) pattern matching-like sum type functions.
As far as I'm aware, no other libraries have a similar feature, and its usefulness can be observed from the json serialization typeclasses that enable any class built as a `Dat` to be transformed to json without any additional code (compare to circe-generic-auto maybe).

Since I've been using this primarily for neovim plugins, https://github.com/tek/ribosome contains a lot of work based on amino and may serve as a good source for example code.

Regarding the performance issue, this was primarily attributed to the lambda syntax stuff, but in general there is unavoidably some runtime logic necessary that would normally be optimized by a compiler.
Anyway, I have been pretty satisfied with the performance lately (I had also put a little time in to optimize some things), so I wouldn't rule out that it can be used competitively for stuff that doesn't do a lot of homogeneous computation like linear algebra.
The typeclass system needs to look up instances based on involved types, which produces some overhead, but it memoizes methods in python classes after the first use so that should amortize mostly. Only classes that aren't summoned by concrete objects, but types (like the json codec does) will have that overhead every time.

Since I have built this entirely for my own requirements, I'm pretty biased as to the general suitability of the lib, but given the utter inadequacy of virtually all of the python ecosystem for advanced FP, especially when you're used to scala idioms, this is the best you can get.

**Comment by mredaelli** [comment]
Thanks for the detailed answer!

Yeah, I was happy to see that the typeclasses are modelled after cats :)

This confirms that amino does sound like the best alternative - even though low adoption and your moving to Haskell remain question marks. But I will give it a try, and see if I can make a good case for it at work (I also have little interest in using Python for my own stuff).

**Comment by tek** [comment]
certainly a very interesting endeavor :smile: are your colleagues familiar with FP? I couldn't imagine you'd be able to convince pythonistas to adopt this.

**Comment by mredaelli** [comment]
I just started there, so I'm not sure, but I lean towards a no :smile:

**Comment by tek** [comment]
then best of luck :wink:
